### ISSUE TITLE
Support for Puppet 4

### ISSUE THREAD

**Issue by genebean** [voxpupuli/puppet-augeasproviders_grub#26]
I see that in master the metadata.json says it supports Puppet 4 but the latest release does not... how is the Puppet 4 support coming along?

**Comment by raphink** [comment]
I don't see a reason why it wouldn't work on Puppet 4. Are you seeing a specific failure?

**Comment by genebean** [comment]
Before switching from the latest release to master I did. Was hoping that if the Puppet 4 stuff was stable you'd release a new version so I could get off of the git version. Thanks for the quick reply!

**Comment by raphink** [comment]
There's no changes in types & providers API in Puppet 4. Most of the changes are in the Puppet DSL, so really types & providers for Puppet 3 should just work in Puppet 4 without changes. As far as I know, they just work.

**Comment by trevor-vaughan** [comment]
So far all of the ones that we're using "just work" with Puppet 4 AIO and PE

**Comment by genebean** [comment]
The one that broke for me before switching to master was kernel_parameter. It broke the ability to run the agent. The issue disappeared when switching to master.

**Comment by nmesstorff** [comment]
Same here after changing `stringify_facts = false` in the puppet.conf on the agent (as suggested by puppetlabs as preparation to puppet 4 migration).

Error message on the puppet node:
`Error: /Stage[main]/Main/Node[default]/Kernel_parameter[console]: Could not evaluate: Augeas didn't load /etc/default/grub with Shellvars_list.lns: Iterated lens matched less than it should (line:8, character:0)`

The affected puppet code:
`     kernel_parameter { "console":
       ensure  => present,
       value => "ttyS0,115200n8",
     }`

**Comment by raphink** [comment]
@nmesstorff I'm not sure I see how `stringify_facts = false` could play a role in this really. The error you're reporting says that Augeas was not able to parse the file at `/etc/default/grub` and failed to parse on line 8.

Could you paste that file (or at least line 8) please?

**Comment by jhoblitt** [comment]
puppet 4 is long EOL.
