### ISSUE TITLE
How does one handle kernel parameter changes that call for grub2-mkconfig and reboot ?

### ISSUE THREAD

**Issue by linuxdan** [voxpupuli/puppet-augeasproviders_grub#39]
Example:  (RHEL 7)

kernel_parameter{'ipv6.disable':
  ensure => absent,
}

**Comment by trevor-vaughan** [comment]
I do it this way https://github.com/simp/pupmod-simp-fips/blob/master/manifests/init.pp#L54

Using https://github.com/simp/pupmod-simp-simplib/blob/master/lib/puppet/type/reboot_notify.rb

**Comment by raphink** [comment]
@trevor-vaughan does this use `/var/lib/reboot-required` on OSes that support it?

**Comment by trevor-vaughan** [comment]
@raphink Honestly, I didn't even know that was a thing! But now that I do, it probably should. In this case, I wanted to be able to give useful metadata to the user about *why* the reboot was required and be able to have multiple reasons based on different parts of code.

**Comment by trevor-vaughan** [comment]
@raphink Do you know of a way of definitively detecting if an OS supports that file? It seems like it's a Debian-ish thing. I could always just drop the file in place no matter what but that seems...weird.

**Comment by linuxdan** [comment]
@trevor-vaughan 
Does your code actually cause a reboot or just create a notification?

**Comment by linuxdan** [comment]
@raphink 
/var/lib/reboot-required looks like a Debian thing. 
Even so, I can find no guidance about using it.
Most of the Red Hat/CentOS search results refer to yum’s `needs-restarting`, but this operation does not use yum.

**Comment by jhoblitt** [comment]
What I do is notify https://forge.puppet.com/modules/puppetlabs/reboot. Works great.
